name: tedarik_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  mobile_scanner: ^2.0.0
  url_launcher: ^6.2.5
  http: 1.4.0
  web3dart: ^2.6.0
  convert: ^3.1.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  qr_flutter: ^4.0.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1  
  gallery_saver_plus: ^3.0.1
  fl_chart: ^0.66.0
  flutter_charts: ^0.5.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/abi/ProductTracking.json
    - assets/images/
    - assets/icons/
    - .env
